################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_RT "rt")
    if (NOT PC_RT_FOUND)
        pkg_check_modules(PC_RT "rt")
    endif (NOT PC_RT_FOUND)
    if (PC_RT_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_RT_CFLAGS} ${PC_RT_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_RT_INCLUDE_HINTS ${PC_RT_INCLUDE_DIRS} ${PC_RT_INCLUDE_DIRS}/*)
        set(PC_RT_LIBRARY_HINTS ${PC_RT_LIBRARY_DIRS} ${PC_RT_LIBRARY_DIRS}/*)
    endif(PC_RT_FOUND)
endif (NOT MSVC)

find_path (
    RT_INCLUDE_DIRS
    NAMES time.h
    HINTS ${PC_RT_INCLUDE_HINTS}
)

find_library (
    RT_LIBRARIES
    NAMES rt
    HINTS ${PC_RT_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    RT
    REQUIRED_VARS RT_LIBRARIES RT_INCLUDE_DIRS
)
mark_as_advanced(
    RT_FOUND
    RT_LIBRARIES RT_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
