/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "czmq.h"
#include "org_zeromq_czmq_Zactor.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zactor__1_1new (JNIEnv *env, jclass c, jlong task, jlong args)
{
    //  Disable CZMQ signal handling; allow Java to deal with it
    zsys_handler_set (NULL);
    jlong new_ = (jlong) (intptr_t) zactor_new ((zactor_fn *) (intptr_t) task, (void *) (intptr_t) args);
    return new_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zactor__1_1destroy (JNIEnv *env, jclass c, jlong self)
{
    zactor_destroy ((zactor_t **) &self);
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zactor__1_1send (JNIEnv *env, jclass c, jlong self, jlong msg_p)
{
    jint send_ = (jint) zactor_send ((zactor_t *) (intptr_t) self, (zmsg_t **) (intptr_t) &msg_p);
    return send_;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zactor__1_1recv (JNIEnv *env, jclass c, jlong self)
{
    jlong recv_ = (jlong) (intptr_t) zactor_recv ((zactor_t *) (intptr_t) self);
    return recv_;
}

JNIEXPORT jboolean JNICALL
Java_org_zeromq_czmq_Zactor__1_1is (JNIEnv *env, jclass c, jlong self)
{
    jboolean is_ = (jboolean) zactor_is ((void *) (intptr_t) self);
    return is_;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zactor__1_1resolve (JNIEnv *env, jclass c, jlong self)
{
    jlong resolve_ = (jlong) (intptr_t) zactor_resolve ((void *) (intptr_t) self);
    return resolve_;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zactor__1_1sock (JNIEnv *env, jclass c, jlong self)
{
    jlong sock_ = (jlong) (intptr_t) zactor_sock ((zactor_t *) (intptr_t) self);
    return sock_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zactor__1_1setDestructor (JNIEnv *env, jclass c, jlong self, jlong destructor)
{
    zactor_set_destructor ((zactor_t *) (intptr_t) self, (zactor_destructor_fn *) (intptr_t) destructor);
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zactor__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zactor_test ((bool) verbose);
}

