/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zactor__ZactorFn */

#ifndef _Included_org_zeromq_czmq_Zactor__ZactorFn
#define _Included_org_zeromq_czmq_Zactor__ZactorFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zactor__ZactorFn
 * Method:    __new
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zactor_00024_1ZactorFn__1_1new
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zeromq_czmq_Zactor__ZactorFn
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zactor_00024_1ZactorFn__1_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
