/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zactor_ZactorFn */

#ifndef _Included_org_zeromq_czmq_Zactor_ZactorFn
#define _Included_org_zeromq_czmq_Zactor_ZactorFn
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
