/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zactor */

#ifndef _Included_org_zeromq_czmq_Zactor
#define _Included_org_zeromq_czmq_Zactor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __new
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zactor__1_1new
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zactor__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __send
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zactor__1_1send
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __recv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zactor__1_1recv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __is
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zactor__1_1is
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __resolve
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zactor__1_1resolve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __sock
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zactor__1_1sock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __setDestructor
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zactor__1_1setDestructor
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zactor
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zactor__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
